service: ical-merge-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  
functions:
  main:
    handler: main.handler
    events:
      - httpApi:
          path: /
          method: get